alias startpg='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias rfd="java -jar ~/.bin/rmr.jar"
alias startqfs="launchctl load /usr/local/etc/qfs/homebrew.mxcl.qfs-meta.plist && launchctl load /usr/local/etc/qfs/homebrew.mxcl.qfs-chunk.plist"
alias stopqfs="launchctl unload /usr/local/etc/qfs/homebrew.mxcl.qfs-meta.plist && launchctl unload /usr/local/etc/qfs/homebrew.mxcl.qfs-chunk.plist"
alias check-js-pr="git diff-index --name-only master | grep '.*\.js' | xargs $(npm bin)/eslint"
alias recreate-db="rake db:drop && rake db:create && rake db:structure:load"
alias docker-load-fixtures="docker-compose run --rm testing bash -l -c 'rake db:fixtures:load'"
alias check-rb-pr="git diff-index --name-only master | grep '\.rb$' | xargs bundle exec rubocop"
alias ecr-login="eval $(aws ecr get-login --no-include-email)"
